#!/bin/bash
# setup-codex.sh - Configure OpenAI Codex CLI to mirror Claude Code environment
#
# Creates:
#   ~/.codex/config.toml       - MCP servers, notifications, settings
#   ~/.codex/AGENTS.md         - Symlink to ~/.claude/CLAUDE.md
#   ~/.agents/skills/cp/       - Commit and push skill
#   ~/.agents/skills/cppr/     - Commit, push, PR, watch actions skill
#   ~/.agents/skills/merge/    - Merge PR to main skill
#   ~/.agents/skills/daily/    - Daily startup workflow skill

set -euo pipefail

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
SKILLS_HOME="$HOME/.agents/skills"

# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────
info()  { printf '  \033[32m✓\033[0m %s\n' "$1"; }
warn()  { printf '  \033[33m!\033[0m %s\n' "$1"; }
error() { printf '  \033[31m✗\033[0m %s\n' "$1" >&2; }

create_dir() {
    mkdir -p "$1"
    info "Created $1"
}

# ─────────────────────────────────────────────────────────────
# Preflight checks
# ─────────────────────────────────────────────────────────────
preflight() {
    local missing=0

    if ! command -v codex &> /dev/null; then
        error "codex not found - install with: npm install -g @openai/codex"
        missing=1
    fi

    if ! command -v uv &> /dev/null; then
        warn "uv not found - Things MCP server will not work"
    fi

    if ! command -v gh &> /dev/null; then
        warn "gh not found - git workflow skills (cppr, merge) will be limited"
    fi

    if [[ ! -d "/Applications/Unblocked.app" ]]; then
        warn "Unblocked.app not found - context engine MCP will not work"
    fi

    if [[ $missing -eq 1 ]]; then
        error "Missing required dependencies. Aborting."
        exit 1
    fi
}

# ─────────────────────────────────────────────────────────────
# config.toml
# ─────────────────────────────────────────────────────────────
write_config() {
    create_dir "$CODEX_HOME"

    if [[ -f "$CODEX_HOME/config.toml" ]]; then
        cp "$CODEX_HOME/config.toml" "$CODEX_HOME/config.toml.bak"
        warn "Backed up existing config.toml to config.toml.bak"
    fi

    cat > "$CODEX_HOME/config.toml" << TOML
# Codex CLI configuration
# Generated by setup-codex.sh - mirrors Claude Code environment

model = "gpt-5-codex"
model_reasoning_effort = "high"
experimental_use_rmcp_client = true

# Accept CLAUDE.md as fallback project instructions
project_doc_fallback_filenames = ["CLAUDE.md", ".agents.md"]
project_doc_max_bytes = 65536

# Notification hook (tmux window highlighting)
notify = ["${HOME}/.claude/scripts/notify-done.sh"]

# ─────────────────────────────────────────────────────────────
# MCP Servers
# ─────────────────────────────────────────────────────────────

# Unblocked - organizational context, Jira/Slack/PR data retrieval
[mcp_servers.unblocked]
command = "${HOME}/.unblocked/agent/node/bin/node"
args = ["/Applications/Unblocked.app/Contents/Resources/mcp/server.js", "--client", "mcpVscode"]
startup_timeout_sec = 15

# Grafana - dashboards, Prometheus, Loki logs
[mcp_servers.grafana]
url = "https://http-grafana-mcp.fetchrewards.com/"

# Things 3 - task management
[mcp_servers.things]
command = "uv"
args = ["--directory", "${HOME}/code/utilities/things-mcp", "run", "things_server.py"]
startup_timeout_sec = 15

# Atlassian - Jira + Confluence (run \`codex mcp login atlassian\` after setup)
[mcp_servers.atlassian]
url = "https://mcp.atlassian.com/v1/mcp"
TOML

    info "Wrote $CODEX_HOME/config.toml"
}

# ─────────────────────────────────────────────────────────────
# AGENTS.md (symlink to shared CLAUDE.md)
# ─────────────────────────────────────────────────────────────
write_agents_md() {
    local source="$HOME/.claude/CLAUDE.md"
    local target="$CODEX_HOME/AGENTS.md"

    if [[ ! -f "$source" ]]; then
        warn "~/.claude/CLAUDE.md not found - skipping AGENTS.md"
        return
    fi

    if [[ -f "$target" ]] && [[ ! -L "$target" ]]; then
        cp "$target" "$target.bak"
        warn "Backed up existing AGENTS.md to AGENTS.md.bak"
    fi

    ln -sf "$source" "$target"
    info "Symlinked $target -> $source"
}

# ─────────────────────────────────────────────────────────────
# Skills
# ─────────────────────────────────────────────────────────────
write_skill() {
    local name="$1"
    local content="$2"
    local dir="$SKILLS_HOME/$name"

    create_dir "$dir"
    printf '%s\n' "$content" > "$dir/SKILL.md"
    info "Wrote skill: $name"
}

write_skills() {
    write_skill "cp" "---
name: cp
description: Use when the user asks to commit and push changes to the remote repository
---

# Commit and Push

1. Commit all staged changes with an appropriate message
2. Push to remote"

    write_skill "cppr" "---
name: cppr
description: Use when the user asks to commit, push, open a PR, and watch CI actions
---

# Commit, Push, PR, Watch

1. Commit all staged changes with an appropriate message
2. Push to remote
3. Open a pull request using \`gh pr create\`
4. Watch GitHub Actions with \`gh run watch\` and notify when they pass or fail"

    write_skill "merge" "---
name: merge
description: Use when the user asks to merge the current branch PR to main
---

# Merge PR to Main

1. Find the PR for the current branch using \`gh pr view\`
2. Merge the PR using \`gh pr merge\` with squash
3. Switch back to main and pull latest
4. Ask if user wants to delete the local feature branch and worktree if applicable"

    write_skill "daily" "---
name: daily
description: Use when starting the workday to review tasks, calendar, and set up daily note
---

# Daily Startup

## Steps

1. **Calendar** - Fetch today's meetings via \`icalbuddy eventsToday\`
2. **Things Today** - Get critical work tasks using the Things MCP \`get_today\` tool
3. **Things Inbox** - Surface items needing triage using the Things MCP \`get_inbox\` tool
4. **RFDs** - Check for RFDs needing review or action using Unblocked
5. **Summarize** - Present overview and offer to create daily note

## Output Format

\`\`\`
## Today's Focus

### Meetings
- 9:00 AM - Standup
- 2:00 PM - 1:1 with Person Name

### Critical Tasks
- [ ] Task from Things Today

### Inbox (needs triage)
- Item needing triage

### RFDs to Review
- RFD-123: Title (awaiting review)

---
Ready to create daily note? (Daily/{date}.md)
\`\`\`

## Daily Note

If user confirms, create \`Daily/YYYY-MM-DD.md\` in Obsidian vault with:
- Frontmatter with date and tags
- Meetings section pre-filled
- Space for daily log

## Tools Used

- \`icalbuddy eventsToday\` - calendar events
- Things MCP \`get_today\` - today's tasks
- Things MCP \`get_inbox\` - inbox items
- Unblocked context engine - find RFDs where Jake Huggart is mentioned"
}

# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────
main() {
    echo "Setting up Codex CLI to mirror Claude Code environment..."
    echo ""

    preflight
    write_config
    write_agents_md
    write_skills

    echo ""
    echo "Done! Next steps:"
    echo "  1. Run: codex mcp login atlassian"
    echo "  2. Verify: codex --ask-for-approval never \"List your available MCP tools\""
}

main "$@"
